version: "2"
services:
  spring-batch:
    image: spring-batch
    ports:
      - "8081:8080"
    networks:
      - spring-batch-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - spring-batch-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=person  

networks:
  spring-batch-mysql: 
